#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6FE19F21451C9A2B (reubenhwk@gmail.com)
#
Name     : radvd
Version  : 2.18
Release  : 3
URL      : http://www.litech.org/radvd/dist/radvd-2.18.tar.xz
Source0  : http://www.litech.org/radvd/dist/radvd-2.18.tar.xz
Source1  : http://www.litech.org/radvd/dist/radvd-2.18.tar.xz.asc
Summary  : A Router Advertisement daemon
Group    : Development/Tools
License  : BSD-4-Clause
Requires: radvd-bin = %{version}-%{release}
Requires: radvd-license = %{version}-%{release}
Requires: radvd-man = %{version}-%{release}
Requires: radvd-services = %{version}-%{release}
BuildRequires : bison
BuildRequires : flex
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(systemd)
BuildRequires : systemd-dev

%description
radvd is the router advertisement daemon for IPv6.  It listens to router
solicitations and sends router advertisements as described in "Neighbor
Discovery for IP Version 6 (IPv6)" (RFC 2461).  With these advertisements
hosts can automatically configure their addresses and some other
parameters.  They also can choose a default router based on these
advertisements.

Install radvd if you are setting up IPv6 network and/or Mobile IPv6
services.

%package bin
Summary: bin components for the radvd package.
Group: Binaries
Requires: radvd-license = %{version}-%{release}
Requires: radvd-services = %{version}-%{release}

%description bin
bin components for the radvd package.


%package license
Summary: license components for the radvd package.
Group: Default

%description license
license components for the radvd package.


%package man
Summary: man components for the radvd package.
Group: Default

%description man
man components for the radvd package.


%package services
Summary: services components for the radvd package.
Group: Systemd services

%description services
services components for the radvd package.


%prep
%setup -q -n radvd-2.18
cd %{_builddir}/radvd-2.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1578638248
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1578638248
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/radvd
cp %{_builddir}/radvd-2.18/COPYRIGHT %{buildroot}/usr/share/package-licenses/radvd/0dbb3270e5e0b70b5af9f3c6b7663fc83d06e482
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/radvd
/usr/bin/radvdump

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/radvd/0dbb3270e5e0b70b5af9f3c6b7663fc83d06e482

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/radvd.conf.5
/usr/share/man/man8/radvd.8
/usr/share/man/man8/radvdump.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/radvd.service
